### ISSUE TITLE
Gerber Files Corrupted

### ISSUE THREAD

**Issue by eugenosm** [luwii/Smart-IC-Tester#1]
Gerber files (`ICTester_Gerbers.zip`) are actually not Gerber, nor Eagle CAD files. This is a corrupted github html. Please check it.
Possible there was an error while upload, or some github issue...

```html






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-Wr5yTs8gD42bv1Ll5KLXr7cXzuVcbKOcuHmifgt/6YlZuluDTyAJnfnYhNYKpgVK1F51ks8Y2QA+XENQoMp/PA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-5abe724ecf200f8d9bbf52e5e4a2d7af.css" />
  
    <link crossorigin="anonymous" media="all" integrity="sha512-/Kdj6P6WRk2SG1AIisQL1y+ZbNnTv1a+pX/4yP0e13VjZ5s+uYXnQOx+NKpXpBPqzyB/JscjxW7D30/a5DneZA==" rel="stylesheet" href="https://github.githubassets.com/assets/github-fca763e8fe96464d921b50088ac40bd7.css" />
.  .  .
```

**Comment by luwii** [comment]
Thanks - Uploaded a new file. Hopefully that is better

Sent from my phone

On 26 Sep 2024, at 17:27, Eugene Mazitov ***@***.***> wrote:

﻿

Gerber files (ICTester_Gerbers.zip) are actually not Gerber, nor Eagle CAD files. This is a corrupted github html. Please check it.
Possible there was an error while upload, or some github issue...



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-Wr5yTs8gD42bv1Ll5KLXr7cXzuVcbKOcuHmifgt/6YlZuluDTyAJnfnYhNYKpgVK1F51ks8Y2QA+XENQoMp/PA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-5abe724ecf200f8d9bbf52e5e4a2d7af.css" />

    <link crossorigin="anonymous" media="all" integrity="sha512-/Kdj6P6WRk2SG1AIisQL1y+ZbNnTv1a+pX/4yP0e13VjZ5s+uYXnQOx+NKpXpBPqzyB/JscjxW7D30/a5DneZA==" rel="stylesheet" href="https://github.githubassets.com/assets/github-fca763e8fe96464d921b50088ac40bd7.css" />
.  .  .
